theme: just-the-docs
title: "Classics 199: Digital Mythology"


aux_links:
  "Course Google Drive": 
    - "https://drive.google.com/drive/u/0/folders/16AqmgQKUxF0Rx-1DEO5KVcVYedKjzXiH"
  "juliahub's AskAI":
    - "https://juliahub.com/ui/AskAI"





footer_content: "Classics 199, <i>Digital Mythology</i>. All material on this web site is available under the Creative Commons Attribution Share-Alike license <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC BY-SA 4.0 <img height=\"15\" width=\"80\" src=\"https://mirrors.creativecommons.org/presskit/buttons/80x15/png/by-sa.png\" /></a> on <a href=\"https://github.com/neelsmith/digitalmyth\">github</a>."    